Fix deprecation warning
On Julia 1.7.2 with `--depwarn=error` this expression `Vararg{<:AbstractArray}` causes the error
```julia
ERROR: Wrapping `Vararg` directly in UnionAll is deprecated (wrap the tuple instead).
Stacktrace:
 [1] UnionAll(v::TypeVar, t::Any)
   @ Core ./boot.jl:255
 [2] top-level scope
   @ REPL[25]:1
```